name: Deploy to Server

on:
  pull_request:
    # Change to merge when implemented (still beta)      
    types: [closed] 
    branches:
      - master
    
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.4
      if: github.event.pull_request.merged == true
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        password: ${{ secrets.id }}
        port: ${{ secrets.port }}
        script: ${{ secrets.script }}
